spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DATABASE_NAME:odds}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # trailing slash is important!
          issuer-uri: ${ISSUER_URI}
          audience: ${AUDIENCE}

# Log HTTP requests and responses
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    com.bhanna.oddsapi: TRACE
    root: ERROR

server:
  error:
    include-message: always

odds-api:
  bookmakers: ${BOOKMAKERS}
  markets: ${MARKETS}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  openai:
    url: ${OPENAI_URL}
  odds-client:
    token: ${ODDS_API_KEY}
springdoc:
  swagger-ui:
    path: /swagger-ui.html